### ISSUE TITLE
Save User Wallet in the users Table

### ISSUE THREAD

**Issue by sotoJ24** [safetrustcr/Backend#10]
**Description**  
Add functionality to store user wallet addresses in the `users` table. This will enable linking users to their blockchain wallets for identity verification, transactions, and other wallet-related features.  

**Problem**  
The platform requires a way to associate users with their blockchain wallets to:  
- Enable secure wallet-based authentication.  
- Support wallet-driven transactions and interactions.  
- Facilitate integration with Web3 functionalities, such as token management and on-chain operations.  

**Requirements**  
- Add a `wallet_address` field to the `users` table with appropriate data type and size.  
- Ensure `wallet_address` is unique to prevent duplicate entries.  
- Validate the wallet address format upon insertion to ensure compatibility with blockchain standards.  
- Update any related APIs or database access layers to include the `wallet_address` field.

**Comment by rvalenciano** [comment]
This was already solved here:

https://github.com/safetrustcr/Backend/pull/5
