### ISSUE TITLE
 Create escrow_transactions and related tables for Trustless API Integration

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Backend#20]
Create database schema to track all Stellar blockchain escrow operations through Trustless Work API, including contract deployment, funding, completion, cancellation, and HTTP response tracking.

## Problem
We need to:
- Track all Trustless API interactions and responses
- Handle XDR transaction signing workflow
- Support the complete escrow lifecycle (create, fund, complete, cancel)
- Monitor HTTP responses and handle errors
- Maintain audit trail of all operations
- Track unsigned/signed transactions

### Migration Files

Create new migration:
```bash
hasura migrate create create_escrow_system
```

#### `up.sql`:
```sql
-- Create transaction type enum
CREATE TYPE escrow_transaction_type AS ENUM (
    'CREATE_ESCROW',
    'FUND_ESCROW',
    'COMPLETE_ESCROW',
    'CANCEL_ESCROW',
    'REFUND_ESCROW'
);

-- Create escrow status enum
CREATE TYPE escrow_status AS ENUM (
    'PENDING',
    'AWAITING_SIGNATURE',
    'SIGNED',
    'PROCESSING',
    'COMPLETED',
    'FAILED',
    'CANCELLED',
    'REFUNDED'
);

-- Create XDR status enum
CREATE TYPE xdr_status AS ENUM (
    'PENDING',
    'GENERATED',
    'SIGNED',
    'SUBMITTED',
    'CONFIRMED',
    'FAILED'
);

-- Create main escrow_transactions table
CREATE TABLE escrow_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    bid_request_id UUID REFERENCES bid_requests(id) ON DELETE CASCADE,
    
    -- Trustless API fields
    engagement_id TEXT,
    contract_id TEXT,
    signer_address TEXT,
    
    -- Transaction details
    transaction_type escrow_transaction_type NOT NULL,
    status escrow_status NOT NULL DEFAULT 'PENDING',
    
    -- HTTP response tracking
    http_status_code INTEGER,
    http_response_body JSONB,
    http_error_details JSONB,
    
    -- Amount and deposit tracking
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    initial_deposit_percentage INTEGER DEFAULT 50,
    
    -- Cancellation details
    cancellation_reason TEXT,
    cancelled_by TEXT REFERENCES users(id),
    refund_status escrow_status,
    
    -- Metadata and timestamps
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    
    -- Constraints
    CONSTRAINT valid_http_status CHECK (
        http_status_code >= 100 AND 
        http_status_code < 600
    ),
    CONSTRAINT valid_contract_id_when_needed CHECK (
        (transaction_type IN ('FUND_ESCROW', 'COMPLETE_ESCROW', 'CANCEL_ESCROW')) = 
        (contract_id IS NOT NULL)
    )
);

-- Create XDR transactions tracking table
CREATE TABLE escrow_xdr_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    escrow_transaction_id UUID REFERENCES escrow_transactions(id) ON DELETE CASCADE,
    xdr_type escrow_transaction_type NOT NULL,
    unsigned_xdr TEXT NOT NULL,
    signed_xdr TEXT,
    status xdr_status DEFAULT 'PENDING',
    signing_address TEXT,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_xdr_fields CHECK (
        (status = 'SIGNED' AND signed_xdr IS NOT NULL) OR
        (status != 'SIGNED')
    )
);

-- Create API calls tracking table
CREATE TABLE escrow_api_calls (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    escrow_transaction_id UUID REFERENCES escrow_transactions(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    method TEXT NOT NULL,
    request_body JSONB,
    http_status_code INTEGER,
    response_body JSONB,
    error_details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_http_status CHECK (
        http_status_code >= 100 AND 
        http_status_code < 600
    ),
    CONSTRAINT valid_http_method CHECK (
        method IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH')
    )
);

-- Create required indexes
CREATE INDEX idx_escrow_transactions_bid ON escrow_transactions(bid_request_id);
CREATE INDEX idx_escrow_transactions_contract ON escrow_transactions(contract_id);
CREATE INDEX idx_escrow_transactions_status ON escrow_transactions(status);
CREATE INDEX idx_escrow_transactions_type_status ON escrow_transactions(transaction_type, status);
CREATE INDEX idx_escrow_xdr_transaction ON escrow_xdr_transactions(escrow_transaction_id);
CREATE INDEX idx_escrow_api_calls_transaction ON escrow_api_calls(escrow_transaction_id);
CREATE INDEX idx_escrow_api_calls_status ON escrow_api_calls(http_status_code);

[Previous triggers and functions remain the same...]
```

#### `down.sql`:
```sql
-- Drop indexes
DROP INDEX IF EXISTS idx_escrow_transactions_bid;
DROP INDEX IF EXISTS idx_escrow_transactions_contract;
DROP INDEX IF EXISTS idx_escrow_transactions_status;
DROP INDEX IF EXISTS idx_escrow_transactions_type_status;
DROP INDEX IF EXISTS idx_escrow_xdr_transaction;
DROP INDEX IF EXISTS idx_escrow_api_calls_transaction;
DROP INDEX IF EXISTS idx_escrow_api_calls_status;

-- Drop tables
DROP TABLE IF EXISTS escrow_api_calls;
DROP TABLE IF EXISTS escrow_xdr_transactions;
DROP TABLE IF EXISTS escrow_transactions;

-- Drop types
DROP TYPE IF EXISTS escrow_transaction_type;
DROP TYPE IF EXISTS escrow_status;
DROP TYPE IF EXISTS xdr_status;
```

## Workflow Diagram
```mermaid
stateDiagram-v2
    [*] --> CREATE_ESCROW
    CREATE_ESCROW --> FUND_ESCROW: Deploy Success
    FUND_ESCROW --> COMPLETE_ESCROW: Fund Success
    FUND_ESCROW --> CANCEL_ESCROW: Cancel Request
    CANCEL_ESCROW --> REFUND_ESCROW: Process Refund
    
    state CREATE_ESCROW {
        [*] --> PENDING
        PENDING --> AWAITING_SIGNATURE
        AWAITING_SIGNATURE --> PROCESSING
        PROCESSING --> COMPLETED
        PROCESSING --> FAILED
    }
```

### Create Escrow
```json
{
  "transaction_type": "CREATE_ESCROW",
  "status": "AWAITING_SIGNATURE",
  "engagement_id": "test",
  "amount": 1000.00,
  "http_status_code": 200,
  "http_response_body": {
    "status": "SUCCESS",
    "unsignedTransaction": "AAAAAgAAAABfQAm/gS..."
  }
}
```

### XDR Transaction
```json
{
  "escrow_transaction_id": "uuid",
  "xdr_type": "CREATE_ESCROW",
  "unsigned_xdr": "AAAAAgAAAABfQAm/gS...",
  "status": "GENERATED"
}
```

### API Call
```json
{
  "endpoint": "/escrow/create",
  "method": "POST",
  "request_body": {
    "engagementId": "test",
    "signer": "GD2SVFOJ..."
  },
  "http_status_code": 200,
  "response_body": {
    "status": "SUCCESS"
  }
}
```

## Prerequisites
- [ ] PostGIS extension enabled
- [ ] Bid requests table created
- [ ] Users table created
- [ ] Trustless API credentials configured

## Success Criteria
- [ ] All tables created with correct constraints
- [ ] Triggers working properly
- [ ] XDR transaction tracking working
- [ ] HTTP response tracking working
- [ ] Status transitions validated

**Comment by Michaelkingsdev** [comment]
I’d like to work on this.

**Comment by jaykayudo** [comment]
May I try my hand at this?

**Comment by Cbiux** [comment]
I have experience in developing systems related to this sector and would like to participate in the implementation of this topic. I am committed to moving it forward no matter what the cost.

Also, as a member of the Web3 community in Costa Rica, this project is particularly interesting to me. I am good at working on the backend, and I am sure that I can add value to make this solution work efficiently and reliably.

I look forward to collaborating with you on this challenge.

**Comment by josephpdf** [comment]
Hi! @rvalenciano
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Understand the Requirements:**
- Review the issue details to understand the specific requirements for implementing the "Paid State Bid Request" page.
2. **Set Up the Development Environment:**
- Ensure the development environment is configured correctly for frontend development.
3. **Create the Component Structure:**
- Develop the necessary components such as `InvoiceHeader`, `InvoiceDetails`, `PaymentTable`, `ProcessTimeline`, and `NotesSection`.
- Organize these components under `src/features/bids/components/`.
4. **Implement the Main Page:**
- Develop the `PaidStateBidRequest.tsx` page under `src/features/bids/pages/`.
- Use hardcoded data initially to simulate the dynamic data until backend integration is available.
5. **Design the Layout:**
- Create a two-column layout with the left column for invoice details and the right column for notes and process timelines.
- Ensure the design matches the provided mockup.
6. **Test the Implementation:**
- Verify that the page displays all invoice details correctly and shows the payment status clearly.
- Ensure the layout is responsive and works well on different screen sizes.
7. **Prepare for Backend Integration:**
- Ensure the frontend is ready for eventual backend integration by using placeholders for dynamic data.

**Comment by CristopherAguilar10** [comment]
Hi, I am interested in working on this issue. I have experience developing in Java, C# and Python, and have previously worked with relational databases.
I believe I can implement the proposed schema ensuring that the tables, relationships and validations work correctly. In addition, I can perform tests to validate the entire escrow lifecycle flow and ensure that data is recorded as expected.
I am excited for the opportunity to contribute to this project.

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


I propose creating a database schema to capture the complete escrow lifecycle, including creation, funding, completion, cancellation, and HTTP response tracking. This involves designing tables for escrow transactions, XDR transactions, and API call logs, along with validations for HTTP status codes and required data. Indexes will optimize query performance, while triggers and functions ensure data integrity and proper state transitions. Additionally, error handling, rate limiting, and support for cancellation and refund flows will be implemented to ensure smooth operation.

**Comment by rvalenciano** [comment]
Hey @mariocodecr , feel free to work on this issue and ping me if you have any question
