### ISSUE TITLE
Set up Karate Testing Framework for GraphQL API - Users Module

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Backend#29]
Set up automated testing for our Hasura GraphQL API using Karate framework, focusing initially on the users and authentication functionality.

Follow this [tutorial](https://hasura.io/blog/testing-hasura-graphql-apis-with-karate)
 
## Problem
We need to:
- Set up Karate testing environment
- Test user-related GraphQL operations
- Verify Firebase auth integration
- Test users
- Generate test reports

## Solution

A possible solution looks like:

### Project Structure
```plaintext
/tests
├── docker-compose.test.yml
├── karate-config.js
├── logback-test.xml
├── karate/
│   ├── features/
│   │   ├── auth/
│   │   │   ├── login.feature
│   │   │   └── permissions.feature
│   │   └── users/
│   │       ├── create.feature
│   │       ├── query.feature
│   │       └── wallets.feature
│   └── helpers/
│       └── schemas.js
└── results/
```

### Example Test Feature
```gherkin
# karate/features/users/query.feature
Feature: User Queries

Background:
  * url HASURA_ENDPOINT
  * def query = read('queries/list-users.graphql')

Scenario: Query Current User
  Given header Authorization = 'Bearer ' + firebase_token
  And header x-hasura-role = 'user'
  And request { 
    query: 'query GetCurrentUser { users_by_pk(id: "' + user_id + '") { id email last_seen } }'
  }
  When method post
  Then status 200
  And match response.data.users_by_pk.id == user_id
  And match response.errors == '#notpresent'

Scenario: Query User Wallets
  Given header Authorization = 'Bearer ' + firebase_token
  And def query = read('queries/get-user-wallets.graphql')
  And def variables = { userId: '#(user_id)' }
  And request { query: '#(query)', variables: '#(variables)' }
  When method post
  Then status 200
  And match response.data.user_wallets[0] contains { is_primary: true }
  And match response.errors == '#notpresent'
```

### Example GraphQL Queries
```graphql
# karate/features/users/queries/get-user-wallets.graphql
query GetUserWallets($userId: String!) {
  user_wallets(
    where: {user_id: {_eq: $userId}}
    order_by: {is_primary: desc}
  ) {
    id
    wallet_address
    chain_type
    is_primary
    created_at
  }
}
```

### User Authentication
- [ ] Test Firebase token validation
- [ ] Verify JWT claims
- [ ] Test invalid tokens
- [ ] Check token expiration

### User Queries
- [ ] Get current user
- [ ] List user roles
- [ ] Query user wallets
- [ ] Test permission boundaries

### User Roles
- [ ] Verify tenant role assignments
- [ ] Verify landlord role assignments
- [ ] Test role-based access control
- [ ] Test role transitions

### User Wallets
- [ ] Query wallet information
- [ ] Verify primary wallet logic
- [ ] Test wallet address uniqueness
- [ ] Test chain type validation

### Error Scenarios
- [ ] Missing authentication
- [ ] Invalid user IDs
- [ ] Unauthorized access
- [ ] Invalid wallet addresses

### Docker Configuration
```yaml
version: '3.8'
services:
  karate:
    image: karate-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./karate:/karate
      - ./results:/results
    environment:
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
    depends_on:
      - graphql-engine
```

### Karate Config with Firebase Support
```javascript
// karate-config.js
function fn() {
  var env = karate.env || 'dev';
  var config = {
    env: env,
    HASURA_ENDPOINT: java.lang.System.getenv('HASURA_ENDPOINT'),
    HASURA_ADMIN_SECRET: java.lang.System.getenv('HASURA_ADMIN_SECRET'),
    FIREBASE_API_KEY: java.lang.System.getenv('FIREBASE_API_KEY')
  };
  
  // Setup Firebase test tokens
  if (env == 'dev') {
    // Add test user tokens
    config.tenant_token = 'test-tenant-token';
    config.landlord_token = 'test-landlord-token';
  }
  
  return config;
}
```

## Success Criteria
- [ ] User query tests passing
- [ ] Role verification working
- [ ] Wallet tests implemented
- [ ] Error scenarios covered
- [ ] Test reports generated

## Prerequisites
- [ ] Test users created
- [ ] Test wallets configured

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

Can i handle this task? i can take care of it.

**Comment by sasasamaes** [comment]
I would love to help with this task!
I am a sensei of a developer community called dev.f and a maintainer of revolutionary farmer and I have 5 years of experience as a full stack developer, I have experience in Javascript, Cairo, Python. This task seems like a great opportunity to learn a little more about docker, hasura and if I find it challenging:
this is my github: https://github.com/sasasamaes

**Comment by abdegenius** [comment]
I’d like to resolve this.

**Comment by diegoTech14** [comment]
Hello @sasasamaes just assigned to you, let us know if you have any question. 🚀

**Comment by diegoTech14** [comment]
Hello @sasasamaes, how's the progress?

**Comment by 0xdevcollins** [comment]
@diegoTech14 Can I take this up?

**Comment by Benjtalkshow** [comment]
@diegoTech14 @rvalenciano 

I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

Can i handle this task? i can take care of it.

**Comment by Michaelkingsdev** [comment]
Can i jump on this?

**Comment by mimisavage** [comment]
I can handle this , please kindly assign

**Comment by olisaagbafor** [comment]
Can I handle this task?

**Comment by nora360** [comment]
Let me handle this issue!

**Comment by diegoTech14** [comment]
Hey @olisaagbafor, just assigned to you, let us know if you have any question please! 🚀

**Comment by olisaagbafor** [comment]
@diegoTech14 please you can review my PR

**Comment by diegoTech14** [comment]
> @diegoTech14 please you can review my PR

Hi sir! yes, I will review ASAP, thanks 🚀
