### ISSUE TITLE
 Create Email Verification System

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Backend#32]
# Implement a standalone email verification system using our existing Hasura setup.

## Database Changes

```sql
-- Add verification related columns to users table
ALTER TABLE users
ADD COLUMN verification_code TEXT,
ADD COLUMN verification_code_expires_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN is_email_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN verification_attempts INTEGER DEFAULT 0,
ADD COLUMN last_verification_request TIMESTAMP WITH TIME ZONE;

-- Add constraints
ALTER TABLE users
ADD CONSTRAINT valid_verification_code 
    CHECK (verification_code ~ '^[0-9]{6}$'),
ADD CONSTRAINT max_verification_attempts 
    CHECK (verification_attempts <= 5);

-- Create index for faster verification queries
CREATE INDEX idx_email_verification ON users(email, verification_code) 
WHERE is_email_verified = FALSE;
```

## Hasura Actions

For a guide on Hasura actions:

https://hasura.io/docs/2.0/actions/overview/

```yaml
actions:
  - name: sendVerificationCode
    definition:
      kind: synchronous
      handler: '{{ACTION_BASE_URL}}/send-verification'
      forward_client_headers: true
    permissions:
      - role: anonymous
  
  - name: verifyEmailCode
    definition:
      kind: synchronous
      handler: '{{ACTION_BASE_URL}}/verify-code'
      forward_client_headers: true
    permissions:
      - role: anonymous
```

## GraphQL Types

```graphql
# Action definitions
type Mutation {
  sendVerificationCode(email: String!): VerificationResponse!
  verifyEmailCode(email: String!, code: String!): VerificationResponse!
}

# Custom types
type VerificationResponse {
  success: Boolean!
  message: String!
  expiresAt: timestamptz
}

# Queries for checking status
type Query {
  checkVerificationStatus(email: String!): VerificationStatus!
}

type VerificationStatus {
  isVerified: Boolean!
  canResendCode: Boolean!
  nextResendTime: timestamptz
}
```

## Action Handlers (Node.js)

```javascript
// handlers/verification.js

// Generate verification code
const generateVerificationCode = () => {
  return Math.floor(100000 + Math.random() * 900000).toString();
};

// Send verification code
app.post('/send-verification', async (req, res) => {
  const { email } = req.body.input;
  const code = generateVerificationCode();
  const expiresAt = new Date(Date.now() + 15 * 60000); // 15 minutes

  try {
    // Update user with new code
    await hasuraClient.request(`
      mutation UpdateVerificationCode($email: String!, $code: String!, $expiresAt: timestamptz!) {
        update_users(
          where: { email: { _eq: $email } }
          _set: {
            verification_code: $code,
            verification_code_expires_at: $expiresAt,
            verification_attempts: 0
          }
        ) {
          affected_rows
        }
      }
    `, { email, code, expiresAt });

    // Send email with code -> For this part lets simulate this as we havent defined an email provider.

    await sendVerificationEmail(email, code); 

    res.json({
      success: true,
      message: "Verification code sent",
      expiresAt
    });
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Failed to send verification code"
    });
  }
});

// Verify code
app.post('/verify-code', async (req, res) => {
  const { email, code } = req.body.input;

  try {
    const result = await hasuraClient.request(`
      mutation VerifyCode($email: String!, $code: String!) {
        update_users(
          where: {
            email: { _eq: $email },
            verification_code: { _eq: $code },
            verification_code_expires_at: { _gt: "now()" },
            is_email_verified: { _eq: false }
          }
          _set: {
            is_email_verified: true,
            verification_code: null
          }
        ) {
          affected_rows
        }
      }
    `, { email, code });

    if (result.update_users.affected_rows > 0) {
      res.json({
        success: true,
        message: "Email verified successfully"
      });
    } else {
      res.json({
        success: false,
        message: "Invalid or expired code"
      });
    }
  } catch (error) {
    res.status(400).json({
      success: false,
      message: "Verification failed"
    });
  }
});
```

## Security Considerations
1. Rate limiting on code requests
2. Maximum verification attempts
3. Code expiration
4. Secure code storage
5. Audit logging

## Success Criteria
- [ ] Database schema updated
- [ ] Actions implemented and tested
- [ ] Email sending working
- [ ] Rate limiting implemented
- [ ] Error handling complete
- [ ] Audit logging implemented

## Migration Strategy
```sql
-- Up Migration
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- [Previous ALTER TABLE statements]

-- Down Migration
ALTER TABLE users
DROP COLUMN verification_code,
DROP COLUMN verification_code_expires_at,
DROP COLUMN is_email_verified,
DROP COLUMN verification_attempts,
DROP COLUMN last_verification_request;

DROP INDEX IF EXISTS idx_email_verification;
```

**Comment by amJoe-dev** [comment]
Hello am a backend developer, can i pls be assigned this issues i really love to make it my first contribution to the community

**Comment by 0xElectrifier** [comment]
Hello, I'm Electrifier, a backend dev proficient in building scalable secure backend systems with Django and ExpressJs. I would love to take on this task.
Estimated Time of delivery is 24hours.

**Comment by Jagadeeshftw** [comment]
I’m interested in taking up this issue.
With my experience in back-end development, I can implement the functionality and ensure it integrates smoothly with the existing system.
I can deliver a PR within 12-24 hours. Please assign this issue to me.

**Comment by olisaagbafor** [comment]
I'd love to give this a go.

**Comment by martinvibes** [comment]
hey sir i would like to work on this issue 
i'm a frontend dev, blockchain
kindly assign and i would get to work right away

**Comment by ikemHood** [comment]
Would love to tackle this!

**Comment by 3th-Enjay** [comment]
Can I start working on this?

**Comment by Aditya-040** [comment]
I’d like to resolve this.

**Comment by 0xElectrifier** [comment]
> Hello, I'm Electrifier, a backend dev proficient in building scalable secure backend systems with Django and ExpressJs. I would love to take on this task. Estimated Time of delivery is 24hours.

### **Proposed Approach**
**Database Updates:**

- Add columns (verification_code, verification_code_expires_at, etc.) and constraints (e.g., valid codes, max attempts) to the users table.
- Create an index on email and verification_code for fast queries.

**Hasura Actions:**

- Define sendVerificationCode and verifyEmailCode actions with anonymous role permissions.
- Add custom types for responses and verification status.

**Backend Handlers:**

- /send-verification: Generate and store a code, reset attempts, and simulate/send email.
- /verify-code: Validate code, mark email as verified, and clear the code.
- Implement rate limiting, secure code storage, and proper error handling.

**Security:**

- Rate limit code requests, enforce max attempts, log actions, and ensure code expiry.

**Success:**

- Database, Hasura actions, and backend fully tested and functional.
- Emails delivered successfully, with all security measures in place.

**Comment by nora360** [comment]
I'd love to work on this!
pls assign me...

**Comment by emarc99** [comment]
Can I work on this, please?
I have experience of databases and node/python. Let me do this.

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way.

May I pick this up?

**Comment by DotworldX** [comment]
Can I tackle this one?

**Comment by CEOliam** [comment]
I'd love to work on this!

**Comment by Abeeujah** [comment]
Hi, pretty clear and descriptive workflow to achieving the result, you've specified in the issues description, I'm a [GraphQL Developer Associate](https://www.apollographql.com/tutorials/certifications/3ba14812-919a-4024-a9b6-e918db6855f0) can I work on this issue?
