### ISSUE TITLE
Seed for apartment_images table🌱

### ISSUE THREAD

**Issue by DiegoB1911** [safetrustcr/Backend#51]
## Objective
Create a comprehensive seed script for the apartment_images table with realistic test data to facilitate development and testing.

### Requirements
- Generate seed data for at least 2 different apartments
- Include realistic image URLs
- Ensure proper UUID generation and referencing

### Implementation Checklist

- [ ] Create initial seed data script
- [ ] Include comments explaining the data generation logic
- [ ] Test with existing apartment IDs

### Considerations

1. Use uuid_generate_v4() for ID generation
2.  Reference existing apartment id's
3. Populate all relevant columns

### SQL Table
``` sql
CREATE TABLE apartment_images (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    apartment_id UUID NOT NULL REFERENCES apartments(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
```

### Acceptance criteria
A complete SQL seed script for apartment_images table

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by Amarjeet325** [comment]
Can I take this issue?

**Comment by mimisavage** [comment]
Is it okay if I take this?

**Comment by salazarsebas** [comment]
Hi safetrustcr,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Write realistic data for the seed script.
- Follow all the requirements described in the issue.
- Write the SQL seed script for two or more apartments.
- Test the SQL seed script.
- Perform all tests and send the pr waiting for feedback.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in building and managing APIs, handling server-side operations, and ensuring robust back-end performance.
Please assign this to me, and I’ll deliver a secure and high-quality PR within 12-24 hours.

**Comment by Nityam573** [comment]
May I take care of this?

**Comment by 1nonlypiece** [comment]
Could I be assigned to this?

**Comment by Josue19-08** [comment]
Hi, I'm Josué, a full-stack developer, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, TypeScript, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm also knowledgeable in databases, including SQL, SQLite, Azure, Mongo, and Elasticsearch. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way.

I will create a comprehensive seed script for the apartment_images table with realistic test data, including at least two different apartments, realistic image URLs, and proper UUID generation. I’ll reference existing apartment IDs and populate all relevant columns, using uuid_generate_v4() for ID generation. As I’m familiar with creating such scripts, I will ensure the data is consistent, add comments explaining the generation logic, and test the script with existing apartment IDs for accuracy.

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

To solve this issue, I'll take the following steps:
1. I'll analyze the apartment_images table, including columns, constraints, and foreign key relationships.
2. I'll use uuid_generate_v4() to generate unique primary keys, populate apartment_id with valid UUIDs from the apartments table, insert image_url with placeholder or realistic URLs and use DEFAULT or manually set timestamps for the uploaded_at column.
3. I'll use SQL INSERT INTO commands to add test data for at least two apartments, ensuring multiple images per apartment.
4. Lastly, I'll test the script to verify proper foreign key references, accurate and complete data insertion and compliance with column constraints.

Kindly assign me please, I'm up for the task.

**Comment by Supa-mega** [comment]
May I pick this up?

**Comment by suhas-sensei** [comment]
Is this issue still available? I'll create a comprehensive seed script for the apartment_images table using real apartment IDs, proper UUID generation, and realistic image URLs. 
Having worked with database seeding and image management systems, I'll ensure referential integrity while providing diverse test data for development.

**Comment by Supa-mega** [comment]
Could I try solving this? this will be my first time contributing to this community and will be extremely   happy to share my expertise and experience of javascript

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Express.js, C#, Cairo, as well as non-relational databases like MongoDB and relational databases such as MSSQL and Oracle.

For this issue, my approach is to:

Examine the schema/Model and write corresponding seed scripts.

my ETA is 2days

**Comment by Josue19-08** [comment]
Thank you Sir! @sotoJ24

**Comment by sotoJ24** [comment]
> Thank you Sir! @sotoJ24

You're welcome @Josue19-08, feel free to ask me anything else via telegram: @sotoj24

**Comment by Josue19-08** [comment]
@sotoJ24 Hello sir! Sorry for the delay, in the next few days I will open my PR.

**Comment by sotoJ24** [comment]
> @sotoJ24 Hello sir! Sorry for the delay, in the next few days I will open my PR.

Hi @Josue19-08, thanks for the update,got it Sir, whatever you request don't hesitate to tell Us

**Comment by sotoJ24** [comment]
Done
