### ISSUE TITLE
Seed Script for bid_requests table 🌱

### ISSUE THREAD

**Issue by DiegoB1911** [safetrustcr/Backend#52]
## Objective
Create a comprehensive seed script for the bid_requests table with realistic test data that simulates various scenarios.

## Requirements
- Generate seed data that covers all possible bid statuses
- Include diverse price ranges and move-in dates
- Ensure proper relationships with apartments and users

## Implementation Checklist
- [ ] Write SQL seed script
- [ ] Verify foreign key constraints with apartments and users tables
- [ ] Ensure data diversity across all statuses
- [ ] Test seed script for consistency
- [ ] Include proper timestamp generation for all date fields
- [ ] Validate price constraints

## Considerations
1. Use uuid_generate_v4() for ID generation
2. Reference existing apartment and user IDs
3. Generate realistic price ranges based on apartment types
4. Create timestamps that make sense (created_at < updated_at)

## SQL Table
```sql
CREATE TABLE bid_requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    apartment_id UUID REFERENCES apartments(id) ON DELETE CASCADE,
    tenant_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    current_status TEXT NOT NULL DEFAULT 'PENDING',
    proposed_price DECIMAL(10,2) NOT NULL CHECK (proposed_price > 0),
    desired_move_in TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT valid_status CHECK (
        current_status IN (
            'PENDING',
            'VIEWED',
            'APPROVED',
            'CONFIRMED',
            'ESCROW_FUNDED',
            'ESCROW_COMPLETED',
            'CANCELLED'
        )
    )
);
```

## Acceptance Criteria
A complete SQL seed script for bid_requests table

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by Amarjeet325** [comment]
May I handle this issue?

**Comment by mimisavage** [comment]
May I pick this up?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in building and managing APIs, handling server-side operations, and ensuring robust back-end performance.
Please assign this to me, and I’ll deliver a secure and high-quality PR within 12-24 hours.

**Comment by Nityam573** [comment]
Let me handle this issue!

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

To solve this issue, I’ll take the following steps:
1.⁠ ⁠First of all I’ll have to understand bid_requests table schema, which includes, foreign key relationships (apartment_id- apartments, tenant_id-users), constraints proposed_price > 0, created_at < updated_at, and valid current_status.
2.⁠ ⁠⁠Then I’ll write an SQL script using INSERT INTO to populate the bid_requests table, I’ll fetch apartment_id and tenant_id from related tables with SELECT ... ORDER BY RANDOM() LIMIT 1, then generate realistic data using functions-
RANDOM() for price ranges, NOW() + INTERVAL for timestamps and also make sure to ensure coverage of all current_status values with multiple INSERT rows.
3.⁠ ⁠I’ll use uuid_generate_v4() for unique IDs, I’ll validate timestamps (created_at vs. updated_at) and make sure to also respect constraints.
4.⁠ ⁠⁠Lastly, I’ll test for constraints like CHECK on current_status and proposed_price, I’ll verify foreign key relationships for apartments and users and run the script in a development environment to confirm data integrity.

Kindly assign me please, I’m up for the task.

**Comment by Supa-mega** [comment]
Can I jump on this task?

**Comment by IsaacHerreraAguilar** [comment]
Hi, I'm Isaac Herrera. I'm a FrontEnd developer with 2 years of experience. I have experience with JS, TS & SQL, and I could help with this issue. I'm very interested.
My proposal would be: 1. Run the command hasura seed create bid_request to create the seed. 2. Create an sql code to insert data into the table. 3. Run the command hasura seed apply to verify the functionality.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando Molina, a full-stack software developer with 2 years of experience. I have worked with languages such as Java, JavaScript, TypeScript, MySQL, C#, and Python. I’m very interested in working on and learning more about this topic.
