### ISSUE TITLE
Seed Script for escrow_api_calls table🌱

### ISSUE THREAD

**Issue by DiegoB1911** [safetrustcr/Backend#54]
## Objective
Create a comprehensive seed script for the escrow_api_calls table that simulates various API interactions with the escrow service.

## Requirements
- Generate seed data covering different API endpoints
- Include various HTTP status codes (success, client errors, server errors)
- Create realistic request and response bodies

## Implementation Checklist
- [ ] Write SQL seed script
- [ ] Verify foreign key constraints with escrow_transactions
- [ ] Generate realistic JSON payloads for requests/responses

## Considerations
1. Use uuid_generate_v4() for ID generation
2. Reference existing escrow_transaction IDs
3. Include all HTTP methods (GET, POST, PUT, DELETE)

## SQL Table
```sql
CREATE TABLE escrow_api_calls (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    escrow_transaction_id UUID REFERENCES escrow_transactions(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    method TEXT NOT NULL,
    request_body JSONB,
    http_status_code INTEGER,
    response_body JSONB,
    error_details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_http_status CHECK (http_status_code >= 100 AND http_status_code < 600),
    CONSTRAINT valid_http_method CHECK (method IN ('GET', 'POST', 'PUT', 'DELETE', 'PATCH'))
);
```

## Acceptance Criteria
A complete SQL seed script for escrow_api_calls table

**Comment by ShantelPeters** [comment]
I'd be happy to do this.

**Comment by Amarjeet325** [comment]
Can I take this issue?

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in building and managing APIs, handling server-side operations, and ensuring robust back-end performance.
Please assign this to me, and I’ll deliver a secure and high-quality PR within 12-24 hours.

**Comment by Nityam573** [comment]
Can I start working on this?

**Comment by 1nonlypiece** [comment]
May I be assigned to this?

**Comment by Superfly101** [comment]
Can I take this issue? This is my first ODHack and I would love to have this as my first issue assigned to me.

Here the approach I would take to create a seed script for the escrow_api_calls table. The first step involves generating seed entries for successful API calls with status codes ranging from 200 to 299, representing common escrow operations such as deposit creation, verification, and release. Next, I'll add representative error scenarios (400-499 client errors, 500-599 server errors) with appropriate error_details and then include realistic JSONB payloads for both request_body and response_body matching actual API contract.

This should take me about 2 days to complete and test locally

**Comment by Josue19-08** [comment]
Hi, I'm Josué, a full-stack developer, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, TypeScript, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way.

I will create a seed script for the escrow_api_calls table to simulate API interactions, covering various endpoints and HTTP status codes. I will use uuid_generate_v4() for ID generation and reference escrow_transactions IDs. I will include all HTTP methods and generate realistic request and response bodies in JSON format.

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

To solve this issue I’ll take the following steps:
1.⁠ ⁠I’ll first of all analyze the escrow_api_calls table structure to identify required fields such as id, escrow_transaction_id, endpoint, http_method, status_code, request_body, response_body, created_at and its foreign key relationship with escrow_transactions.
2.⁠ ⁠⁠Then I’ll use uuid_generate_v4() for unique ID generation, I’ll insert mock data with diverse HTTP methods such as GET, POST, PUT, DELETE and status codes (200, 400, 500), I’ll also populate realistic JSON payloads for request_body and response_body.
3.⁠ ⁠⁠Next I’ll generate diverse API interaction scenarios, including successful operations (201, 200), client errors (400, 404) and server errors (500).
4.⁠ ⁠⁠I’ll ensure foreign key constraints are satisfied by referencing valid escrow_transaction_id from the escrow_transactions table, I’ll make sure to test edge cases like missing or malformed JSON payloads.
5.⁠ ⁠⁠I’ll use JSONB for storing structured data (requests/responses) and write a Node.js script to dynamically generate SQL insert statements for larger datasets.
6.⁠ ⁠⁠Lastly, if you like I can also write tests cases to validate the correctness of seed data, including proper foreign key references, handling of various HTTP methods and status codes and valid JSON serialization for payloads.

Please assign me, I’m ready to work now.

**Comment by Supa-mega** [comment]
Could I take a shot at this?

**Comment by ikezuby2012** [comment]
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Express.js, C#, Cairo, as well as non-relational databases like MongoDB and relational databases such as MSSQL and Oracle.

For this issue, my approach is to:

 Examine the schema/Model and write corresponding seed scripts.

my ETA is 2-3days

**Comment by suhas-sensei** [comment]
Could I take over this issue? I'll create a comprehensive seed script for the escrow_api_calls table with diverse API interactions, including varied HTTP methods and status codes. 
Having experience with API logging systems, I'll ensure realistic request/response JSON payloads while maintaining proper relationships with escrow transactions.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando Molina, a full-stack software developer with 2 years of experience. I have worked with languages such as Java, JavaScript, TypeScript, MySQL, C#, and Python. I’m very interested in working on and learning more about this topic.

**Comment by CoderPrime99** [comment]
Hi! I'm Carlos, a Software Developer with over 2 years of experience. I've worked with C++, Java, and JavaScript, and I'm excited to make my first contribution to OnlyDust. It would be great to contribute to the project's sucess, I am also part of Dojo Coding.

I would start by reviewing the escrow_api_calls table schema and its relationship with the escrow_transactions table to ensure foreign key constraints are met. Using the uuid_generate_v4() function, I’d create unique IDs for each record and reference valid escrow_transaction_id values. For the seed data, I’d simulate realistic API interactions, including various endpoints and HTTP methods (GET, POST, PUT, DELETE), along with meaningful JSON request and response payloads. I’d also include a mix of HTTP status codes, like success, client errors, and server errors, with relevant error details where needed. Once the script is written, I’d test it to confirm it inserts data correctly, respects constraints, and provides a comprehensive dataset for testing the API functionality.
